#!/usr/bin/env bash

# prompt
export PS1="[\u@\h \W]$"
# alias
# export LS_COLORS=`cat ~/.ls_colors`
alias ls="ls --color=auto"
alias ll="ls -lh"
alias la="ls -ah"
alias free="free -h"
alias smi="nvidia-smi"
alias du="du -h"
alias untargz="tar zvfx"

if [ -f ~/.bashrc ] ; then
    source ~/.bashrc
fi

